### ISSUE TITLE
Openfpc-client Doesn't Return After Executing Search

### ISSUE THREAD

**Issue by nehafish** [leonward/OpenFPC#3]
When I run openfpc-client on a cloned branch from Dec 2nd, the client never returns results after accepting username and password. When I include uid and passwd (with AUTH OK from openfpc-queued), the client just hangs. 

I ran tshark to capture the query being sent from openfpc-client. For the command:
bash$ openfpc-client -a search -dtp 443 -proto tcp

The resulting query is sent. I don't see my exact parameters, so it's possible this is the wrong query. What I notice is that the query includes "\x0a" and "\0x9". Placing this command onto the mysql command-line results in an error on parsing those characters:

SELECT start_time,INET_NTOA(src_ip),src_port,INET_NTOA(dst_ip),dst_port,ip_proto,src_bytes, dst_bytes,(src_bytes+dst_bytes) as total_bytes\x0a\x09FROM session IGNORE INDEX (p_key) WHERE unix_timestamp(CONVERT_TZ(`start_time`, '+00:00', @@session.time_zone))  \x0a\x09between 1418084402 and 1418088002 ORDER BY start_time DESC LIMIT 20

On the queued side, the daemon shows the following, while the client hangs infinitely:
Tue Dec  9 00:54:19 2014 GMT: ids_dev COMMS: 127.0.0.1: RID: 2 Search Request
Tue Dec  9 00:54:19 2014 GMT: ids_dev COMMS: 127.0.0.1: RID: 2 Start time=0 End time=0

I would appreciate any help. I noticed there have been many commits the last few days, is now a good time to git pull from this repo?

**Comment by nehafish** [comment]
hello @leonward I believe i have solved this issue. I am almost done implementing stable 0.9 code, I will submit a PR in another couple of days. Many thanks for this great code!

**Comment by leonward** [comment]
Sounds good. I've been working on packaging, documentation and cleaning up a load of minor issues for something I can call a 1.0 release. Would be good to get the fixes in for what you've found before that. 

-L

**Comment by leonward** [comment]
Closing
